#ifndef _UICOMMON_H_
#define _UICOMMON_H_

//message
enum emTouchPcmtMsg{
	emTouchPcmtMsgBgn		=	WM_USER + 1,
		
	WM_MENU_ITEM_CLICK,
	WM_MENU_ITEM_DBCLICK,
	WM_MENU_UPDATE_POS,
	WM_MENU_ITEM_CANCLE,

	WM_SETFULLSCREEN,
	WM_RESTORE_FROM_FULL_SCREEN,
	WM_PIPDLG_SET_PIP_VIEW,
	WM_PIPDLG_CLOSE_PIP_VIEW,

    WM_CALL_ADDR_CHANGED,
	WM_UPDATE_QUICK_CALL_RATE,
    
    WM_REDRAW_UI,
	
	WM_HIDE_WND_CMD,
	WM_HIDE_FINISH_NOTIFY,
	WM_SHOW_FINISH_NOTIFY,

	WM_SHOW_MENUDLG_CMD,

    WM_EDIT_CHANGED,
	WM_EDIT_SETFOCUS,

    WM_SWITCH_IME,

	WM_CLICKIPCTRL,

	WM_STOPSOUNDTIMER,


	WM_STOPGETIPTIMER,

	WM_NET_DISCONNECT,
	WM_NET_IPCONFLICT,

    WM_EVENT_3G_RAS,
    WM_EVENT_PPPoE_RAS,

    WM_UI_WIFI_CLICK_ITEM,
    WM_UI_WIFI_MOVE_ITEM,

	WM_DRAG_OVER, // 拖拽时候鼠标经过 by muxingmao
	WM_DRAG_DROP, // 拖拽结束
	WM_DRAG_ENTER, 
	WM_DRAG_LEAVE, 
	WM_DRAG_BEGIN,
	WM_DRAG_END,


	WM_CALL_BUS_ADD_MT,
	WM_CALL_BUS_REMOVE_MT,
	WM_CALL_BUS_SELECT_MT,
	WM_CALL_BUS_CLEAR,

	WM_CALL_BUS_PRE_ADD_ITEM,
	WM_CALL_BUS_POST_ADD_ITEM,

	WM_CALL_BUS_FULL,
	WM_CALL_BUS_ERROR,

	WM_NET_DIAGNOSES_START,
	WM_NET_DIAGNOSES_PINGING,
	WM_NET_DIAGNOSES_FINISHED,


	WM_DRAGWINDOW_DYNAMIC_START, //拖拽窗口动画开始
	WM_DRAGWINDOW_DYNAMIC_END, //拖拽窗口动画结束

	ev_MtStatus,
	ev_Remove,
	ev_Format,

	emTouchPcmtMsgEnd
};


// 配置项左边的X开始位置
#define CFG_ST_LEFT_X							50
// 配置项右边的X开始位置						
#define CFG_ST_RIGHT_X							800
// 配置项左边的Y开始位置
#define CFG_ST_LEFT_Y							300
// 配置项右边的Y开始位置
#define CFG_ST_RIGHT_Y							300
// 配置项条目上下的间距
#define CFG_ST_SPACE_Y							65
#endif