#ifndef _MTMSGID_H_
#define _MTMSGID_H_

#include "kdvtype.h"

//使用protocol buffer编码的消息，消息id与消息体编码在一块buffer中，对应CMtMsg，当使用OSP传送CMtMsg编码的buffer时，OspPost接口的event参数必须设置为Ev_MtOsp_ProtoBufMsg。
#define EV_MT_PBMSG_BGN 1000
enum EmMtProtoBufEvSegs
{
//系统控制消息段
EVSEG_SYSCTRL_BGN          = (EV_MT_PBMSG_BGN),
EVSEG_SYSCTRL_END          = (EVSEG_SYSCTRL_BGN + 100),

//h323协议消息段
EVSEG_H323_BGN,
EVSEG_H323_END             = (EVSEG_H323_BGN + 1000),

//卫星协议消息段
EVSEG_SAT_BGN,
EVSEG_SAT_END              = (EVSEG_SAT_BGN + 1000),

//协议适配消息段
EVSEG_MTPA_BGN,
EVSEG_MTPA_END             = (EVSEG_MTPA_BGN + 1000),

//IM消息段
EVSEG_IM_BGN,
EVSEG_IM_END               = (EVSEG_IM_BGN + 500),

//MEETING消息段
EVSEG_MEETING_BGN,
EVSEG_MEETING_END          = (EVSEG_MEETING_BGN + 500),

//AGENT消息段
EVSEG_AGENT_BGN,
EVSEG_AGENT_END            = (EVSEG_AGENT_BGN + 300),

//数据协同消息段
EVSEG_DATASERVICE_BGN,
EVSEG_DATASERVICE_END      = (EVSEG_DATASERVICE_BGN + 500),

//微博消息段
EVSEG_MICROBLOG_BGN,
EVSEG_MICROBLOG_END        = (EVSEG_MICROBLOG_BGN + 500),

//设备控制消息段
EVSEG_DEVICE_BGN,
EVSEG_DEVICE_END           = (EVSEG_DEVICE_BGN + 500),

//系统升级消息段
EVSEG_UPGRADE_BGN,
EVSEG_UPGRADE_END          = (EVSEG_UPGRADE_BGN + 200),

//通讯录消息段
EVSEG_CONTACT_BGN,
EVSEG_CONTACT_END          = (EVSEG_CONTACT_BGN + 500),

//misc消息段
EVSEG_MISC_BGN,
EVSEG_MISC_END             = (EVSEG_MISC_BGN + 500),

//网络管理消息段
EVSEG_NETWORK_BGN,
EVSEG_NETWORK_END          = (EVSEG_NETWORK_BGN + 200),

//服务器登录消息段
EVSEG_LOGSERVER_BGN,
EVSEG_LOGSERVER_END        = (EVSEG_LOGSERVER_BGN + 200),

//MP各平台通用消息段
EVSEG_MPCOMMON_BGN,
EVSEG_MPCOMMON_END         = (EVSEG_MPCOMMON_BGN + 200),

//MP windows平台消息段
EVSEG_MPWIN_BGN,
EVSEG_MPWIN_END            = (EVSEG_MPWIN_BGN + 200),

//MP 硬终端平台(linux,android)消息段
EVSEG_MPEMBED_BGN,
EVSEG_MPEMBED_END          = (EVSEG_MPEMBED_BGN + 300),

//MP 移动平台（android，ios）消息段
EVSEG_MPMOBILE_BGN,
EVSEG_MPMOBILE_END         = (EVSEG_MPMOBILE_BGN + 200),

//配置消息段（与Key对应）
EVSEG_CONFIG_BGN,
EVSEG_CONFIG_END        = (EVSEG_CONFIG_BGN + 2000),

//扩展配置消息段（包含一个/多个/部分配置）
EVSEG_CONFIG_EX_BGN,
EVSEG_CONFIG_EX_END     = (EVSEG_CONFIG_EX_BGN + 200),

//消息分发模块消息段
EVSEG_DISPATCH_BGN,
EVSEG_DISPATCH_END         = (EVSEG_DISPATCH_BGN + 100),

//终端客户端接入模块消息段
EVSEG_ACCESS_BGN,
EVSEG_ACCESS_END           = (EVSEG_ACCESS_BGN + 200),

//点播模块消息段
EVSEG_MTVOD_BGN,
EVSEG_MTVOD_END           = (EVSEG_MTVOD_BGN + 200),

//rest模块消息段
EVSEG_REST_BGN,
EVSEG_REST_END           = (EVSEG_REST_BGN + 200),

//record模块消息段
EVSEG_RECORD_BGN,
EVSEG_RECORD_END           = (EVSEG_RECORD_BGN + 200),

//会议管理消息段
EVSEG_REST_MEETING_BGN,
EVSEG_REST_MEETING_END           = (EVSEG_REST_MEETING_BGN + 200),

//rest好友相关消息段
EVSEG_REST_ROSTER_BGN,
EVSEG_REST_ROSTER_END           = (EVSEG_REST_ROSTER_BGN + 200),

//内置mc模块消息段
EVSEG_MTMCSERVICE_BGN,
EVSEG_MTMCSERVICE_END           = (EVSEG_MTMCSERVICE_BGN + 500),


// 诊断消息段
EVSEG_DIAGNOSE_BGN,
EVSEG_DIAGNOSE_END			   = (EVSEG_DIAGNOSE_BGN + 10),


// 横幅台标字幕消息段
EVSEG_TEXTIMAGE_BGN,
EVSEG_TEXTIMAGE_END			   = (EVSEG_TEXTIMAGE_BGN + 50),

// mtsecure消息段
EVSEG_MTSECURE_BGN,
EVSEG_MTSECURE_END			   = (EVSEG_MTSECURE_BGN + 50),

EVSEG_MTAIMSG_BGN,
EVSEG_MTAIMSG_END   =  (EVSEG_MTAIMSG_BGN + 50),


//////////////////////////////////////////////////////////////////////////
// ————————————————华丽分割线————————————————//
//																	    //
//     以下是BLL消息段。用于sdk与mtservice间通讯，无关消息不得乱入         //
//////////////////////////////////////////////////////////////////////////
#define EV_MT_BLLPBMSG_BGN 0x00070000

//BLL系统控制消息段
EVSEG_BLL_SYSCTRL_BGN          = (EV_MT_BLLPBMSG_BGN),
EVSEG_BLL_SYSCTRL_END          = (EVSEG_BLL_SYSCTRL_BGN + 100),

//BLL会议消息段
EVSEG_BLL_CONF_BGN,
EVSEG_BLL_CONF_END             = (EVSEG_BLL_CONF_BGN + 1000),

//BLLIM消息段
EVSEG_BLL_IM_BGN,
EVSEG_BLL_IM_END               = (EVSEG_BLL_IM_BGN + 500),

//BLL MEETING消息段
EVSEG_BLL_MEETING_BGN,
EVSEG_BLL_MEETING_END          = (EVSEG_BLL_MEETING_BGN + 500),

//BLL AGENT消息段
EVSEG_BLL_AGENT_BGN,
EVSEG_BLL_AGENT_END            = (EVSEG_BLL_AGENT_BGN + 300),

//BLL数据协同消息段
EVSEG_BLL_DATASERVICE_BGN,
EVSEG_BLL_DATASERVICE_END      = (EVSEG_BLL_DATASERVICE_BGN + 500),

//BLL微博消息段
EVSEG_BLL_MICROBLOG_BGN,
EVSEG_BLL_MICROBLOG_END        = (EVSEG_BLL_MICROBLOG_BGN + 500),

//BLL设备控制消息段
EVSEG_BLL_DEVICE_BGN,
EVSEG_BLL_DEVICE_END           = (EVSEG_BLL_DEVICE_BGN + 500),

//BLL系统升级消息段
EVSEG_BLL_UPGRADE_BGN,
EVSEG_BLL_UPGRADE_END          = (EVSEG_BLL_UPGRADE_BGN + 200),

//BLL诊断消息段
EVSEG_BLL_DIAGNOSE_BGN,
EVSEG_BLL_DIAGNOSE_END         = (EVSEG_BLL_DIAGNOSE_BGN + 100),

//BLL通讯录消息段
EVSEG_BLL_CONTACT_BGN,
EVSEG_BLL_CONTACT_END          = (EVSEG_BLL_CONTACT_BGN + 500),

//BLL misc消息段
EVSEG_BLL_MISC_BGN,
EVSEG_BLL_MISC_END             = (EVSEG_BLL_MISC_BGN + 500),

//BLL网络管理消息段
EVSEG_BLL_NETWORK_BGN,
EVSEG_BLL_NETWORK_END          = (EVSEG_BLL_NETWORK_BGN + 200),

//BLL服务器登录消息段
EVSEG_BLL_LOGSERVER_BGN,
EVSEG_BLL_LOGSERVER_END        = (EVSEG_BLL_LOGSERVER_BGN + 200),

//BLLMP各平台通用消息段
EVSEG_BLL_MPCOMMON_BGN,
EVSEG_BLL_MPCOMMON_END         = (EVSEG_BLL_MPCOMMON_BGN + 200),

//BLLMP windows平台消息段
EVSEG_BLL_MPWIN_BGN,
EVSEG_BLL_MPWIN_END            = (EVSEG_BLL_MPWIN_BGN + 200),

//BLL MP 硬终端平台(linux,android)消息段
EVSEG_BLL_MPEMBED_BGN,
EVSEG_BLL_MPEMBED_END          = (EVSEG_BLL_MPEMBED_BGN + 300),

//BLL MP 移动平台（android，ios）消息段
EVSEG_BLL_MPMOBILE_BGN,
EVSEG_BLL_MPMOBILE_END         = (EVSEG_BLL_MPMOBILE_BGN + 200),

//BLL配置消息段（与Key对应）
EVSEG_BLL_CONFIG_BGN,
EVSEG_BLL_CONFIG_END        = (EVSEG_BLL_CONFIG_BGN + 2000),

//BLL 扩展配置消息段（包含一个/多个/部分配置）
EVSEG_BLL_CONFIG_EX_BGN,
EVSEG_BLL_CONFIG_EX_END     = (EVSEG_BLL_CONFIG_EX_BGN + 200),

//BLL终端客户端接入模块消息段
EVSEG_BLL_ACCESS_BGN,
EVSEG_BLL_ACCESS_END           = (EVSEG_BLL_ACCESS_BGN + 200),

//BLL点播模块消息段
EVSEG_BLL_MTVOD_BGN,
EVSEG_BLL_MTVOD_END           = (EVSEG_BLL_MTVOD_BGN + 200),

//BLL rest模块消息段
EVSEG_BLL_REST_BGN,
EVSEG_BLL_REST_END           = (EVSEG_BLL_REST_BGN + 200),

//BLL record模块消息段
EVSEG_BLL_RECORD_BGN,
EVSEG_BLL_RECORD_END           = (EVSEG_BLL_RECORD_BGN + 200),

//BLL 会议管理消息段
EVSEG_BLL_REST_MEETING_BGN,
EVSEG_BLL_REST_MEETING_END           = (EVSEG_BLL_REST_MEETING_BGN + 200),

//BLL rest好友相关消息段
EVSEG_BLL_REST_ROSTER_BGN,
EVSEG_BLL_REST_ROSTER_END           = (EVSEG_BLL_REST_ROSTER_BGN + 200),

//BLL内置mc模块消息段
EVSEG_BLL_MTMCSERVICE_BGN,
EVSEG_BLL_MTMCSERVICE_END           = (EVSEG_BLL_MTMCSERVICE_BGN + 500),

//BLL内置sec模块消息段
EVSEG_BLL_MTSEC_BGN,
EVSEG_BLL_MTSEC_END           = (EVSEG_BLL_MTSEC_BGN + 500),

//BLL dcs模块消息段
EVSEG_BLL_DCS_BGN,
EVSEG_BLL_DCS_END           = (EVSEG_BLL_DCS_BGN + 200),

EVSEG_BLL_MTAIMSG_BGN,
EVSEG_BLL_MTAIMSG_END   =  (EVSEG_BLL_MTAIMSG_BGN + 50),

};

#define EV_BGN(SEG) EV_##SEG##_BGN
#define EV_END(SEG) EV_##SEG##_END

#define EV_BLL_BGN(SEG) EV_##SEG##_BLL_BGN
#define EV_BLL_END(SEG) EV_##SEG##_BLL_END


#if !defined(_MESSAGE_HELP_)
#define MESSAGE(m) m,
#define BODY(T, dscrpt)  //T:消息体类型 dscrpt:消息体描述
#endif

#endif