// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvstructupgrade.proto

package com.kedacom.nv.netmanage.protobuf;

public final class StructUpgradePB {
  private StructUpgradePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025nvstructupgrade.proto\022\002nv\032\014nvenum.prot" +
      "o\032\024nvstructcommon.proto\032\022nvstructbase.pr" +
      "otoB4\n!com.kedacom.nv.netmanage.protobuf" +
      "B\017StructUpgradePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kedacom.nv.netmanage.protobuf.EnumPB.getDescriptor(),
          com.kedacom.nv.netmanage.protobuf.StructCommonPB.getDescriptor(),
          com.kedacom.nv.netmanage.protobuf.BasePB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
