/*=============================================================================================
模块名   : logclient
文件名   : logmod.h
功能     : 集中定义日志模块
作者     : ruiyigen
版权     : <Copyright(C) 2003-2015 Suzhou Keda Technology Co., Ltd. All rights reserved.>
=============================================================================================*/
#ifndef _LOGMOD_H_
#define _LOGMOD_H_

#define MDL_DRIVER "MDL_DRIVER"
#define MDL_SYSCTRL "MDL_SYSCTRL"
//#define MDL_IM "MDL_IM"
//#define MDL_REST "MDL_REST"
#define MDL_DSCLIENT "MDL_DSCLIENT"
#define MDL_DSSERVER "MDL_DSSERVER"
#define MDL_CFG "MDL_CFG"
#define MDL_MP "MDL_MP"
#define MDL_NVDEVICE "MDL_NVDEVICE"
#define MDL_NVMFGTEST "MDL_NVMFGTEST"
//#define MDL_NVCONF "MDL_NVCONF"
//#define MDL_NVPA "MDL_NVPA"
//#define MDL_NVH323 "MDL_NVH323"
//#define MDL_NVMC "MDL_NVMC"
#define MDL_NVDISPATCH "MDL_NVDISPATCH"
#define MDL_NVACCESS "MDL_NVACCESS"
#define MDL_AGENT "MDL_AGENT"
//#define MDL_AGENTADP "MDL_AGENTADP"
//#define MDL_MISC "MDL_MISC"
//#define MDL_NVVOD "MDL_NVVOD"
#define MDL_UPGRADE "MDL_UPGRADE"
#define MDL_RECORD "MDL_RECORD"
#define MDL_NVSERVICE "MDL_NVSERVICE"
#define MDL_NVAPI "MDL_NVAPI"
#define MDL_NVAPI_BS "MDL_NVAPI_BS"
//#define MDL_NVAPI_VC "MDL_NVAPI_VC"
//#define MDL_NVAPI_IM "MDL_NVAPI_IM"
//#define MDL_NVAPI_CM "MDL_NVAPI_CM"
//#define MDL_NVAPI_MG "MDL_NVAPI_MG"
//#define MDL_NVAPI_VNC "MDL_NVAPI_VNC"
//#define MDL_NVAPI_DC "MDL_NVAPI_DC"
//#define MDL_NVAPI_DIAGNOSE "MDL_NVAPI_DIAGNOSE"
#define MDL_RPCCLIENT "MDL_RPCCLIENT"
#define MDL_RPCSERVER "MDL_RPCSERVER"
#define MDL_XMLRPC "MDL_XMLRPC"
//#define MDL_SATSERVICE "MDL_SATSERVICE"
//#define MDL_SATSTACK "MDL_SATSTACK"
//#define MDL_DIAGNOSE "MDL_DIAGNOSE"
//#define MDL_NVUI "MDL_NVUI"
//#define MDL_NVUI_CONF "MDL_NVUI_CONF"
//#define MDL_NVUI_CFG "MDL_NVUI_CFG"
//#define MDL_NVUI_VOD "MDL_NVUI_VOD"
//#define MDL_NVUI_CAM "MDL_NVUI_CAM"
//#define MDL_NVUI_MON "MDL_NVUI_MON"
//#define MDL_NVUI_REMOTE "MDL_NVUI_REMOTE"
//#define MDL_NVUI_DG "MDL_NVUI_DG"
//#define MDL_NVUI_CM "MDL_NVUI_CM"
//#define MDL_NVUI_MG "MDL_NVUI_MG"
//#define MDL_NVUI_IM "MDL_NVUI_IM"
//#define MDL_NVUI_DC "MDL_NVUI_DC"
//#define MDL_NVUI_NET "MDL_NVUI_NET"
//#define MDL_NETMAGAGE "MDL_NETMAGAGE"
#define MDL_NVCAPI_JNI "MDL_NVCAPI_JNI"
#define MDL_NVTERINTERFACE "MDL_NVTERINTERFACE"
#define MDL_NVUPGRADESERVER "MDL_NVUPGRADESERVER"
#define MDL_NVAPI_UPGRADE "MDL_NVAPI_UPGRADE"
#define MDL_NVQUICKSHARE "MDL_NVQUICKSHARE"
#define MDL_NVDETECTOR "MDL_NVDETECTOR"
#define MDL_NVAPI_QUICKSHARE "MDL_NVAPI_QUICKSHARE"
#define MDL_NVSUC "MDL_NVSUC"
#define MDL_NVCONSUS "NVCONSUS"

#endif // _LOGMOD_H_