// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struct.proto

#ifndef PROTOBUF_struct_2eproto__INCLUDED
#define PROTOBUF_struct_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "port.pb.h"
#include "enum.pb.h"
#include "structbase.pb.h"
#include "structcommon.pb.h"
#include "structim.pb.h"
#include "structrest.pb.h"
#include "structconf.pb.h"
#include "structagent.pb.h"
#include "structmp.pb.h"
#include "structcfg.pb.h"
#include "structcontacts.pb.h"
#include "structnet.pb.h"
#include "structdevice.pb.h"
#include "structdcs.pb.h"
#include "structkeydriver.pb.h"
// @@protoc_insertion_point(includes)

namespace mt {

// Internal implementation detail -- do not call these.
void MTMSG_API protobuf_AddDesc_struct_2eproto();
void protobuf_AssignDesc_struct_2eproto();
void protobuf_ShutdownFile_struct_2eproto();


// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace mt

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_struct_2eproto__INCLUDED
